package astro;

import java.io.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Main_Menu extends javax.swing.JFrame {

    private Stage_1 stage_1 = new Stage_1();
    private ArrayList<Jugador> jugadores = new ArrayList();
    private static javax.sound.sampled.Clip clip;

    public Main_Menu() throws UnsupportedAudioFileException, IOException, LineUnavailableException {
        initComponents();
        lectura();
        music();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_options = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        button_start = new javax.swing.JButton();
        button_options = new javax.swing.JButton();
        button_about = new javax.swing.JButton();
        label_wallpaper = new javax.swing.JLabel();

        jd_options.setMinimumSize(new java.awt.Dimension(674, 419));
        jd_options.setResizable(false);
        jd_options.getContentPane().setLayout(null);

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Puntaje", "Disparadoras", "Bombas", "Girasoles", "Papas", "Plantas Puestas"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        jd_options.getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 100, 620, 230);

        jButton1.setText("Regresar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jd_options.getContentPane().add(jButton1);
        jButton1.setBounds(10, 360, 98, 29);

        jLabel2.setText("Jugadores en Historia");
        jd_options.getContentPane().add(jLabel2);
        jLabel2.setBounds(250, 60, 140, 16);

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Plants VS Zombies 0.1");
        setBackground(new java.awt.Color(51, 51, 51));
        setForeground(new java.awt.Color(51, 51, 51));
        setMinimumSize(new java.awt.Dimension(640, 480));
        setResizable(false);
        getContentPane().setLayout(null);

        button_start.setText("Start Game");
        button_start.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_startMouseClicked(evt);
            }
        });
        getContentPane().add(button_start);
        button_start.setBounds(510, 350, 112, 29);

        button_options.setText("View History");
        button_options.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_optionsMouseClicked(evt);
            }
        });
        getContentPane().add(button_options);
        button_options.setBounds(510, 380, 110, 29);

        button_about.setText("About");
        button_about.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_aboutMouseClicked(evt);
            }
        });
        button_about.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_aboutActionPerformed(evt);
            }
        });
        getContentPane().add(button_about);
        button_about.setBounds(510, 410, 110, 29);

        label_wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/astro/Wallpaper 640x480.png"))); // NOI18N
        getContentPane().add(label_wallpaper);
        label_wallpaper.setBounds(0, 0, 640, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_aboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_aboutMouseClicked
        JOptionPane.showMessageDialog(Main_Menu.getFrames()[0], "Project Code Name: Astro\nProject Name: Plants VS Zombies Clone\nDeveloper: José Eduardo Hernández\nRelease Date: September 17,2013\nVersion: 1.0.0 BETA");
    }//GEN-LAST:event_button_aboutMouseClicked

    private void button_startMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_startMouseClicked
        this.setVisible(false);
        stage_1.setVisible(true);
    }//GEN-LAST:event_button_startMouseClicked

    private void button_optionsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_optionsMouseClicked
        DefaultTableModel modelo = (DefaultTableModel) tabla.getModel();
        while (modelo.getRowCount() > 0) {
            modelo.removeRow(0);
        }
        tabla.setModel(modelo);
        Object[] row = new Object[7];
        for (int i = 0; i < jugadores.size(); i++) {
            row[0] = jugadores.get(i).getNombre();
            row[1] = jugadores.get(i).getScore();
            row[2] = jugadores.get(i).getShooterCounter();
            row[3] = jugadores.get(i).getBombCounter();
            row[4] = jugadores.get(i).getSunFlowerCounter();
            row[5] = jugadores.get(i).getPotatoCounter();
            row[6] = jugadores.get(i).getTotalPlants();
            modelo.addRow(row);
        }
        tabla.setModel(modelo);
        jd_options.setModal(true);
        jd_options.pack();
        jd_options.setVisible(true);

    }//GEN-LAST:event_button_optionsMouseClicked

    private void button_aboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_aboutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_aboutActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        jd_options.setVisible(false);
    }//GEN-LAST:event_jButton1MouseClicked

    //Metodo para reproducir la musica
    public static void music() throws UnsupportedAudioFileException, IOException, LineUnavailableException {
        File soundFile = new File("./Levels.wav"); //Se encuentra el archivo de musica y se instancia
        AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(soundFile); //Se consigue el InputStream para el archivo de musica
        clip = AudioSystem.getClip(); //Conseguimos un clip para reproducir
        clip.open(audioInputStream); //El compilador abre el clip de musica
        clip.loop(20);
        //clip.start(); //This plays the audio 
    }

    public void lectura() {
        try {
            File archivo = new File("./Jugadores.txt");
            FileReader fr = new FileReader(archivo);
            BufferedReader br = new BufferedReader(fr);
            String linea;
            while ((linea = br.readLine()) != null) {
                String[] lineas = linea.split(",");
                Jugador jugador = new Jugador(lineas[0], Integer.parseInt(lineas[1]), Integer.parseInt(lineas[2]), Integer.parseInt(lineas[3]), Integer.parseInt(lineas[4]), Integer.parseInt(lineas[5]), Integer.parseInt(lineas[6]));
                jugadores.add(jugador);
            }
            fr.close();
        } catch (Exception e) {
            System.out.println("File not found");
        }
    }

    public static void main(String args[]) {
        /* Set the MAC OS X look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new Main_Menu().setVisible(true);
                } catch (UnsupportedAudioFileException | IOException | LineUnavailableException ex) {
                    Logger.getLogger(Main_Menu.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton button_about;
    private javax.swing.JButton button_options;
    private javax.swing.JButton button_start;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JDialog jd_options;
    private javax.swing.JLabel label_wallpaper;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
